---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy-crush
spec:
  replicas: 3
  selector:
    matchLabels:
      app: candy-crush
  template:
    metadata:
      labels:
        app: candy-crush
    spec:
      containers:
      - name: tetris
        image: chotu194/candy:latest
        ports:
        - containerPort: 4000   

---
apiVersion: v1
kind: Service
metadata:
  name: candy-crush-service
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80                 
    targetPort: 4000
  type: LoadBalancer
